import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import React from "react";
import Header from "@/components/Header";
import LenisProvider from "@/components/Lenis";

const inter = Inter({
  subsets: ['latin'],
  weight: ['500', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
      <Header />
      <LenisProvider>
        {children}
      </LenisProvider>
      </body>
    </html>
  );
}
